---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "barbican-exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "barbican-exporter.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "barbican-exporter.selectorLabels" . | nindent 4 }}
  ports:
    - name: {{ .Values.service.name }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
